name: development

on:
  push:
    branches: [main, dev]

jobs:
  execute_sql:
    name: Execute SQL
    environment:
      name: development
    if: github.event.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Execute command
        uses: rhasson/sqlake_action@main
        with:
          worksheet_path: src
          api_key: ${{ secrets.API_KEY }}
      - name: Print Results
        run: |
          cat ${GITHUB_WORKSPACE}/worksheet_output.md >> $GITHUB_STEP_SUMMARY
