name: development

on:
  push:
    branches: [changedfiles]

jobs:
  execute_sql:
    name: Execute SQL
    environment:
      name: development
    if: github.event.ref == 'refs/heads/changedfiles'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed files
        id: cf-step
        uses: tj-actions/changed-files@v29.0.7
        with:
          separator: ","
          files: |
            src/*.sql
      - name: List all added files
        run: |
          for file in ${{ steps.cf-step.outputs.all_changed_files }}; do
            echo "$file was added"
          done
## execute only changed/added SQL files.
## comment this step out and uncomment the next step if you want to execute every SQL
      - name: Execute changed or added files
        uses: rhasson/sqlake_action@main
        with:
           file_list: ${{ steps.cf-step.outputs.all_changed_files }}
           api_key: ${{ secrets.API_KEY }}
## executes every SQL file in order from the given directory
## comment this out and uncomment previous step if you want to only execute changed/added files
#      - name: Execute all SQL
#        uses: rhasson/sqlake_action@main
#        with:
#          path_to_sql: src/
#          api_key: ${{ secrets.API_KEY }}
      - name: Print Results
        run: |
          cat ${GITHUB_WORKSPACE}/execution_output.md >> $GITHUB_STEP_SUMMARY
